swagger: "2.0"
info:
  title: Hello Service
  description: HTTP service for saying hello
  version: ""
host: localhost:9000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /greet/{name}:
    get:
      tags:
      - hellosvc
      summary: greet hellosvc
      operationId: hellosvc#greet
      parameters:
      - name: name
        in: path
        description: Name
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - hellosvc
      summary: Download gen/http/openapi3.json
      operationId: hellosvc#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /openapi.yaml:
    get:
      tags:
      - hellosvc
      summary: Download gen/http/openapi3.yaml
      operationId: hellosvc#/openapi.yaml
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
