openapi: 3.0.3
info:
  title: Hello Service
  description: HTTP service for saying hello
  version: "1.0"
servers:
- url: http://localhost:9000/calc
  description: The hello service
paths:
  /greet/{name}:
    get:
      tags:
      - hellosvc
      summary: greet hellosvc
      operationId: hellosvc#greet
      parameters:
      - name: name
        in: path
        description: Name
        required: true
        schema:
          type: string
          description: Name
          example: Voluptatem voluptatibus itaque omnis.
        example: Sed molestiae.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: string
                example: Aut officiis.
              example: Et cum autem ipsa laboriosam.
  /openapi.json:
    get:
      tags:
      - hellosvc
      summary: Download gen/http/openapi3.json
      operationId: hellosvc#/openapi.json
      responses:
        "200":
          description: File downloaded
  /openapi.yaml:
    get:
      tags:
      - hellosvc
      summary: Download gen/http/openapi3.yaml
      operationId: hellosvc#/openapi.yaml
      responses:
        "200":
          description: File downloaded
components: {}
tags:
- name: hellosvc
  description: The hello service
